<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_module']['notifications_legend'] = 'FrontEdit-Benachrichtigungen';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_edit_notification'][0] = 'Benachrichtigungen';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_edit_notification'][1] = 'Bitte wählen Sie die Benachrichtung aus.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_edit_notification_attributes'][0] = 'Elemente';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_edit_notification_attributes'][1] = 'Bitte wählen Sie die Attribute aus.';