<?php

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_nc_notification']['type']['pct_customcatalog_frontedit']['0']  	= 'CustomCatalog Frontedit';
$GLOBALS['TL_LANG']['tl_nc_notification']['type']['pct_customcatalog_frontedit']['1']  	= 'Benachrichtigungen für Premium Contao Themes CustomCatalog Frontedit';
$GLOBALS['TL_LANG']['tl_nc_notification']['type']['cc_feedit_onsave']  					= 'Bei Speicherung';
$GLOBALS['TL_LANG']['tl_nc_notification']['type']['cc_feedit_ondelete']  				= 'Bei Löschung';
$GLOBALS['TL_LANG']['tl_nc_notification']['type']['cc_feedit_oncreate']  				= 'Bei Erstellung (Erst-Speicherung)';
