<?php

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


$GLOBALS['TL_LANG']['tl_nc_notification']['type']['pct_customcatalog_frontedit']  		= 'CustomCatalog Frontedit';
$GLOBALS['TL_LANG']['tl_nc_notification']['type']['cc_feedit_onsave'][0]  				= 'On save';
$GLOBALS['TL_LANG']['tl_nc_notification']['type']['cc_feedit_ondelete'][0] 				= 'On delete';
$GLOBALS['TL_LANG']['tl_nc_notification']['type']['cc_feedit_oncreate'][0] 				= 'On create (first save)';
